=== VBurachenko/Pagination/src/main/resources/planes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://www.epam.tc.com/planes"
        targetNamespace="http://www.epam.tc.com/planes"
        elementFormDefault="qualified">
    <element name="planes">
        <complexType>
            <sequence>
                <element name="plane" type="tns:Plane" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Plane">
        <sequence>
            <element name="manufacturer" type="string"/>
            <element name="model" type="string"/>
            <element name="origin" type="string"/>
            <element name="type" default="passenger">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="passenger"/>
                        <enumeration value="cargo"/>
                        <enumeration value="military"/>
                        <enumeration value="military-cargo"/>
                        <enumeration value="fighter"/>
                        <enumeration value="bomber"/>
                        <enumeration value="postal"/>
                        <enumeration value="fire-rescue"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="crew" type="positiveInteger"/>
            <element name="passenger_capacity" type="positiveInteger"/>
            <element name="cargo_capacity" type="string"/>
            <element name="price" type="positiveInteger"/>
            <element name="engines" type="tns:Engines"/>
            <element name="parameters" type="tns:Params"/>
        </sequence>
        <attribute name="id" type="string" use="required"/>
    </complexType>

    <complexType name="Engines">
        <sequence>
            <element name="eng_model" type="string"/>
            <element name="eng_type" default="turbofan">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="turbofan"/>
                        <enumeration value="internal combustion"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="amount" type="positiveInteger" use="required"/>
    </complexType>

    <complexType name="Params">
        <sequence>
            <element name="height" type="positiveInteger"/>
            <element name="length" type="positiveInteger"/>
            <element name="wingspan" type="positiveInteger"/>
            <element name="gross_weight" type="positiveInteger"/>
        </sequence>
        <attribute name="color" type="string"/>
        <attribute name="radar" type="boolean"/>
    </complexType>
</schema>

=== VBurachenko/Pagination/src/main/resources/planes.xml
<?xml version="1.0" encoding="UTF-8"?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.epam.tc.com/planes" 
		xsi:schemaLocation="http://www.epam.tc.com/planes planes.xsd">
		
	<plane id="CPL1">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL2">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL3">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL4">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL5">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL6">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL7">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL8">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL9">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
	<plane id="CPL10">
		<manufacturer>Boeing</manufacturer>
		<model>777-312ER</model>
		<origin>USA</origin>
		<type>passenger</type>
		<crew>2</crew>
		<passenger_capacity>368</passenger_capacity>
		<cargo_capacity>200</cargo_capacity>
		<price>650000</price>
		<engines amount="2">
			<eng_model>PW 4098</eng_model>
			<eng_type>turbofan</eng_type>
		</engines>
		<parameters color="green" radar="true">
			<height>18500</height>
			<length>73900</length>
			<wingspan>60900</wingspan>
			<gross_weight>299370</gross_weight>
		</parameters>
	</plane>
</planes>
